---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - name: weather
          image: olaaref/weather
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 500Mi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: "1"
          envFrom:
            - configMapRef:
                name: shared-environment
            - secretRef:
                name: shared-environment
---
apiVersion: v1
kind: Service
metadata:
  name: weather
  labels:
    name: weather
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: weather
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /api/weather-forecast/$1
    nginx.ingress.kubernetes.io/cors-allow-origin: https://localhost:4200
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - http:
        paths:
          - path: /api/weather-forecast/(.*)
            pathType: Prefix
            backend:
              service:
                name: weather
                port:
                  number: 80