
spring:
  application:
    name: weather
  datasource:
    url: jdbc:mysql://localhost:3306/weather_db
    username: weatherApp
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
  servlet:
    context-path: /api/weather-forecast
